"""Cache of each account's last-known instance hardware.

Kaggle has no idle instances: a session exists only while a kernel is
running, so between renders there is no machine to poll. This module
persists the hardware facts observed *during* a run so an idle account
card (Task 4) can show what that account last ran on -- honestly labelled
with its age, never presented as if it were live (see is_stale below).

Storage location: state_dir(), not config_dir(). accounts.json and
settings.json (config_dir) are user intent -- hand-editable, authoritative,
never regenerated by the app on its own. This file is the opposite: it is
entirely app-derived from telemetry, rebuilt from observation rather than
configured, and disposable in the same sense fleet.json (state_dir) is --
losing it costs nothing but a "never run" placeholder until the next
render. That is the same distinction that already put fleet.json in
state_dir() rather than beside accounts.json.

cpu_count, ram_total, and each GPU's model name come from the notebook's
first cell (notebook_builder.py), which prints them once per run to the
same stdout the SSE stream carries -- log_stream.parse_hardware_banner
parses that banner, and blendfleet/ui/dashboard.py wires it through
stream_progress's on_hardware callback (same pattern as on_telemetry).
Per-GPU memory still comes from telemetry (log_stream.parse_telemetry),
which is the only source of the physical GPU *index*; the hardware
banner's nvidia-smi listing has no index column, so its rows are matched
to telemetry's indices by position (both list GPUs in nvidia-smi's own
enumeration order). If the hardware-banner lines never arrive for a run
(the stream drops before the first cell finishes, or a CPU-only session
has no nvidia-smi at all) these fields stay None rather than being
guessed -- the same discipline the rest of this module already applies to
observed_at.
"""
from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path

from blendfleet.platform_paths import state_dir

FILENAME = "instance_state.json"

# Kaggle's own GPU allocation varies between runs -- a P100 last time does
# not guarantee a P100 next time -- so this threshold is not "how long
# until the hardware info is probably wrong", it is "how long a cached
# number may be shown before the UI must stop presenting it as current".
# One day: short enough that a week-old listing never reads as fresh,
# long enough that an account idle overnight does not look artificially
# blank the next morning.
DEFAULT_STALE_AFTER_SECONDS = 24 * 60 * 60.0


@dataclass
class GpuSnapshot:
    """One physical GPU as reported during a run.

    `index` and `mem_total` come from telemetry (TELEMETRY lines carry the
    physical GPU index; the hardware banner's nvidia-smi listing does
    not). `model` comes from the hardware banner instead -- see the module
    docstring -- and is None if that banner never arrived for this run.
    """
    index: int
    mem_total: int  # MiB, as reported by nvidia-smi via TELEMETRY lines
    model: str | None = None  # e.g. "Tesla P100-PCIE-16GB", from the hardware banner


@dataclass
class InstanceSnapshot:
    username: str | None
    gpus: list[GpuSnapshot] = field(default_factory=list)
    cpu_count: int | None = None
    ram_total: float | None = None
    # time.time() epoch seconds. This is the entire honesty mechanism: any
    # caller displaying this snapshot can and must compute its age (via
    # is_stale below) rather than trusting the snapshot to still describe
    # the account's current hardware.
    observed_at: float = 0.0

    def is_stale(self, threshold_seconds: float = DEFAULT_STALE_AFTER_SECONDS,
                 *, now: float | None = None) -> bool:
        """True once this snapshot is older than `threshold_seconds`.

        A snapshot with no recorded age (observed_at defaulted to 0.0 --
        see InstanceStore.load()'s handling of a file written by an older
        version) is always stale: absence of a timestamp must never read
        as "just observed".
        """
        now = time.time() if now is None else now
        return (now - self.observed_at) > threshold_seconds


class InstanceStore:
    def __init__(self, snapshots: dict[str, InstanceSnapshot] | None = None) -> None:
        self._snapshots: dict[str, InstanceSnapshot] = dict(snapshots or {})

    def record(self, label: str, snapshot: InstanceSnapshot) -> None:
        self._snapshots[label] = snapshot

    def get(self, label: str) -> InstanceSnapshot | None:
        return self._snapshots.get(label)

    def _path(self) -> Path:
        return state_dir() / FILENAME

    def save(self) -> None:
        data = {
            label: {
                "username": s.username,
                "gpus": [asdict(g) for g in s.gpus],
                "cpu_count": s.cpu_count,
                "ram_total": s.ram_total,
                "observed_at": s.observed_at,
            }
            for label, s in self._snapshots.items()
        }
        self._path().write_text(json.dumps(data, indent=2), encoding="utf-8")

    @classmethod
    def load(cls) -> "InstanceStore":
        p = state_dir() / FILENAME
        if not p.exists():
            return cls()
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            # Corrupt or unreadable file -- same principle as Settings.load:
            # a bad file on disk must not brick the app, it must just fall
            # back to "no history yet" for every account.
            return cls()
        snapshots: dict[str, InstanceSnapshot] = {}
        for label, d in data.items():
            if not isinstance(d, dict):
                continue  # one malformed entry must not lose every account's history
            gpus = [
                GpuSnapshot(index=g["index"], mem_total=g["mem_total"],
                           model=g.get("model"))
                for g in d.get("gpus", []) or []
                if isinstance(g, dict) and "index" in g and "mem_total" in g
            ]
            snapshots[label] = InstanceSnapshot(
                username=d.get("username"),
                gpus=gpus,
                cpu_count=d.get("cpu_count"),
                ram_total=d.get("ram_total"),
                # Missing entirely (a file written before this field
                # existed) defaults to epoch 0 -- maximally stale -- rather
                # than "now", which would silently lie about freshness.
                observed_at=d.get("observed_at") or 0.0,
            )
        return cls(snapshots)
